site_name: Self-service User Documentation
site_description: 'SSA test'
site_author: 'DIGIT D1'
docs_dir: docs
repo_name: 'gjacopo/test-mkdocs'
repo_url: 'https://github.com/gjacopo/test-mkdocs'
nav:
    - Home: index.md
    - About: about.md
    - Tools: 
      - KNIME:
        - tools/KNIME/anomaly-detection-R.md
#theme: readthedocs
theme: 
  name: 'material'
  logo: 'https://github.com/ec-europa/digit-dataplatform/tree/master/docs/docs/img/ec_logo.jpeg'
  favicon: 'https://github.com/ec-europa/digit-dataplatform/tree/master/docs/docs/img/favicon.ico'
